### ISSUE TITLE
Parser can't handle using some function names as column id

### ISSUE THREAD

**Issue by machow** [datacamp/antlr-plsql#16]
cc @colinricardo 

`SELECT date FROM y` chokes the parser, but `SELECT date1 FROM y` doesn't.

**Comment by machow** [comment]
@colinricardo how much of a priority is this? Do you know if/when it would block course development?

**Comment by colinricardo** [comment]
@machow not a priority I don't think! A quick fix would be to change the `data` column in the database to something less offensive like `timestamp`. Thoughts?

**Comment by machow** [comment]
Ah, I spaced out and forgot that the column in the db is named `date`--I'll just fix it this week, since it will probably be an inconvenience throughout the sql courses!

**Comment by machow** [comment]
a bit easier than expected! Should be updated on sqlwhat-viewer also.
