### ISSUE TITLE
testing deployments to PyPI

### ISSUE THREAD

**Issue by machow** [datacamp/antlr-plsql#18]
Yesterday, I updated antlr-plsql to create a Speaker instance from `antlr_plsql/speaker.yml`. However, because I didn't tell the package to contain the `speaker.yml` file, it did not include it in the PyPI release. This caused the library to raise an error on import.

Unfortunately, because the unit tests passed on every step leading up to release, and the exercise validator isn't testing `courses-intro-sql` yet, I didn't notice until people were testing course exercises. 

It might not be worth the extra effort, but before deploying I can pin to courses-intro-sql to make sure the exercises pass.

**Comment by filipsch** [comment]
I don't think it's worth the extra effort; the course will launch very soon, and from then on, we have a bunch of production exercises that will run `antlr_psql` and corresponding sanity check for future courses in the works...
