### ISSUE TITLE
Bad support for aliases inside join statements

### ISSUE THREAD

**Issue by filipsch** [datacamp/antlr-plsql#29]
Look at [this example](https://ast-viewer.datacamp.com/static/index.html#/editor?code=SELECT%20a%20FROM%20co%20INNER%20JOIN%20ec%20ON%20co.code%20%3D%20ec.code&start=sql_script&grammar=plsql). The alias of the inner join is parsed properly, but the tree representation turns it into an `Unshaped` node while it should be an `AliasExpr`.

@machow The `plsql.g4` file doesn't need changing for this, I think, but the `ast.py` file does. Is this correct? Do you have time to pair on this at some point?

**Comment by machow** [comment]
@filipsch I'm probably doing something wrong but I can't see the unshaped node. Happy to pair whenever is useful!

![image](https://user-images.githubusercontent.com/2574498/44098098-4af763fa-9fad-11e8-8c4c-04bfdd83b962.png)

**Comment by filipsch** [comment]
@machow Sorry, had a wrong example in there. [This example](https://ast-viewer.datacamp.com/static/index.html#/editor?code=SELECT%20a%20FROM%20co%20AS%20c%20INNER%20JOIN%20ec%20AS%20e%20ON%20c.code%20%3D%20e.code&start=sql_script&grammar=plsql) would show it:

```sql
SELECT a FROM co AS c INNER JOIN ec AS e ON c.code = e.code
```

![image](https://user-images.githubusercontent.com/5768479/44098619-f3cec968-9fe0-11e8-9354-3a33d04897b8.png)

**Comment by machow** [comment]
Ah, I think that's the alias piece I mention in issue #30

> 2. implement some AST structure for table aliases (see [this query](https://ast-viewer.datacamp.com/static/index.html#/editor?code=SELECT%20local_name,%20subquery.lang_num%0AFROM%20countries,%0A%20%20%28SELECT%20code,%20COUNT%28%2a%29%20AS%20lang_num%0A%20%20%20FROM%20languages%0A%20%20%20GROUP%20BY%20code%29%20AS%20subquery%0AWHERE%20countries.code%20%3D%20subquery.code%0AORDER%20BY%20lang_num%20DESC%3B&start=sql_script&grammar=plsql))

**Comment by hermansje** [comment]
This is what it looks like now:
<img width="692" alt="Screenshot 2019-03-25 at 23 56 04" src="https://user-images.githubusercontent.com/3393736/54959512-9d39b800-4f59-11e9-8cab-098aa2fd7ee8.png">

[ast-viewer](https://ast-viewer.datacamp.com/editor?code=SELECT%20a%20FROM%20co%20AS%20c%20INNER%20JOIN%20ec%20AS%20e%20ON%20c.code%20%3D%20e.code&start=sql_script&grammar=plsql)
